[workspace]
members = ["cli", "core", "provider-openai", "runtime", "tui"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
futures = "0.3"
jsonschema = { version = "0.54.0", default-features = false }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["rt", "sync", "macros", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }

[profile.release]
lto = "thin"
strip = true

[profile.dev]
debug = 0

[profile.test]
debug = 0

[patch.crates-io]
crossterm = { git = "https://github.com/openai-oss-forks/crossterm", rev = "45fecb9508105988f42fe6ff0441783ed3717f92" }
