[package]
edition.workspace = true
license.workspace = true
name = "antex-home"
version.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
antex-extension-api = { workspace = true }
antex-utils-absolute-path = { workspace = true }
tokio = { workspace = true, features = ["fs"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
