mod appearance;
mod assistant_directives;
mod clipboard_copy;
mod clipboard_html;
mod clipboard_paste;
mod color;
mod composer;
mod custom_terminal;
mod diff_model;
mod diff_render;
mod display_paths;
mod editor_types;
mod foreground;
mod frontend;
mod frontend_layout;
mod insert_history;
mod key_hint;
mod keymap;
mod keymap_config;
mod line_truncation;
mod markdown;
mod markdown_normalize;
mod markdown_paths;
mod markdown_render;
mod markdown_text_merge;
mod mascot;
mod mascot_palette;
mod overlay;
mod pager;
mod paste_burst;
mod picker;
mod presentation_commands;
mod prompt;
mod render;
mod session;
mod settings;
mod startup;
mod style;
mod table_detect;
mod terminal_detection;
mod terminal_guard;
mod terminal_hyperlinks;
mod terminal_palette;
mod terminal_probe;
#[cfg(test)]
mod test_backend;
mod textarea;
mod transcript;
mod tui;
mod vim_search;
mod width;
mod wrapping;

pub use appearance::StartupMascotSkin;
pub use clipboard_paste::ImageSource;
pub use clipboard_paste::parse_image_path;
pub use frontend::run;
pub use pager::TextPage;
pub use picker::PickerItem;
pub use picker::PickerSpec;
pub use session::CommandEffect;

#[cfg(test)]
mod fork_visual_tests;

mod history_reflow;
mod status_line;
mod working_indicator;
pub use session::Session;
pub use session::SessionView;
pub use settings::Settings;
