[package]
name = "antex-mcp-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "antex-mcp-server"
path = "src/main.rs"

[lib]
name = "antex_mcp_server"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
antex-arg0 = { workspace = true }
antex-config = { workspace = true }
antex-core = { workspace = true }
antex-home = { workspace = true }
antex-image-generation-extension = { workspace = true }
antex-exec-server = { workspace = true }
antex-extension-api = { workspace = true }
antex-features = { workspace = true }
antex-git-attribution = { workspace = true }
antex-login = { workspace = true }
antex-otel = { workspace = true }
antex-protocol = { workspace = true }
antex-skills-extension = { workspace = true }
antex-utils-cli = { workspace = true }
antex-utils-json-to-toml = { workspace = true }
rmcp = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
shlex = { workspace = true }
tokio = { workspace = true, features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

[dev-dependencies]
app_test_support = { workspace = true }
antex-utils-absolute-path = { workspace = true }
antex-shell-command = { workspace = true }
core_test_support = { workspace = true }
mcp_test_support = { workspace = true }
os_info = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
wiremock = { workspace = true }
