[package]
edition.workspace = true
license.workspace = true
name = "antex-git-attribution"
version.workspace = true

[lib]
name = "antex_git_attribution"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
antex-backend-client = { workspace = true }
antex-extension-api = { workspace = true }
antex-http-client = { workspace = true }
antex-login = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }
