[package]
edition.workspace = true
license.workspace = true
name = "antex-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
antex-protocol = { workspace = true }
antex-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
