[package]
name = "antex-exec-server-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "antex_exec_server_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
antex-file-system = { workspace = true }
antex-network-proxy = { workspace = true }
antex-protocol = { workspace = true }
antex-shell-command = { workspace = true }
antex-utils-path-uri = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision", "raw_value"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
