[package]
edition.workspace = true
license.workspace = true
name = "antex-core-api"
version.workspace = true

[lib]
doctest = false
name = "antex_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
antex-app-server-protocol = { workspace = true }
antex-arg0 = { workspace = true }
antex-analytics = { workspace = true }
antex-config = { workspace = true }
antex-core = { workspace = true }
antex-extension-api = { workspace = true }
antex-home = { workspace = true }
antex-history = { workspace = true }
antex-image-generation-extension = { workspace = true }
antex-exec-server = { workspace = true }
antex-features = { workspace = true }
antex-login = { workspace = true }
antex-model-provider-info = { workspace = true }
antex-models-manager = { workspace = true }
antex-protocol = { workspace = true }
antex-state = { workspace = true }
antex-utils-absolute-path = { workspace = true }
