load("//:defs.bzl", "antex_rust_crate")

antex_rust_crate(
    name = "plugin",
    compile_data = glob(
        include = ["**"],
        allow_empty = True,
        exclude = [
            "**/* *",
            "BUILD.bazel",
            "Cargo.toml",
        ],
    ),
    crate_name = "antex_plugin",
)
