[package]
edition.workspace = true
license.workspace = true
name = "antex-plugin"
version.workspace = true

[lib]
doctest = false
name = "antex_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
antex-config = { workspace = true }
antex-protocol = { workspace = true }
antex-utils-absolute-path = { workspace = true }
antex-utils-path-uri = { workspace = true }
antex-utils-plugins = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
