[package]
name = "antex-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
antex-core = { path = "../core" }
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm", "layout-cache", "underline-color"] }
tokio.workspace = true

[dev-dependencies]
pretty_assertions = "1"
insta = "1"
